name: Release

on:
  push:
    tags:
      - 'v*.*.*' # Adjust this pattern according to your versioning scheme

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Git credentials
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate changelog
        run: npx conventional-changelog-cli -p angular -i CHANGELOG.md -s -r 0

      - name: Commit changelog
        run: |
          git add CHANGELOG.md
          git commit -m "chore(release): update changelog"

      - name: Push changes
        uses: actions/github-script@v6
        with:
          script: |
            const ref = context.ref.replace('refs/tags/', '');
            await github.rest.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${ref}`,
              sha: context.sha,
              force: true
            });

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false

      - name: Trigger Vercel Deployment
        run: |
          curl -X POST "${{ secrets.VERCEL_API_ENDPOINT }}" \
          -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}"
